### ISSUE TITLE
Kafka Streams or Connector API support

### ISSUE THREAD

**Issue by MuhammadFaizanKhan** [feaselkl/Kafka-Net#1]
Do there any code sample available for Streams or Connector API?

**Comment by feaselkl** [comment]
Unfortunately, no.  This talk is specifically about the .NET API and it does not support Streams or Connector.  I've upvoted the Kafka Streams issue on the Confluent Kafka.NET driver and would love to see movement there, but unless that happens, we won't have that ability.
